### ISSUE TITLE
Use Pull Requests for changes to easy the tracking of them

### ISSUE THREAD

**Issue by onhate** [hesselbom/y-dynamodb#1]
Hi, 

I would like to suggest the use of PRs for the changes applied to this repo to facilitate the tracking of the changes, I see there were changes in the past few days but I have no idea what was changed an if that could break applications out there.

**Comment by hesselbom** [comment]
Good point! I kinda see this project at this point in time as a WIP so it's not exactly battle-tested just yet. But even so it's open source and people are of course bound to use it so I'll make sure to use PRs from now on for changes. :)
